import { StyleSheet } from 'react-native';
// E04845 FFFFFF
const styles = StyleSheet.create({
    contReg:{
        backgroundColor: '#FFFFFF',
        height: 450,
        width: 400,
        borderTopLeftRadius: 80,
        borderTopRightRadius: 80,
        marginBottom: -70,
        marginTop: 300,
    },
    textReg:{
        color: '#E04845',
        marginTop: 20,
        marginLeft: 150,
        fontSize: 20,
    },
    textLineR:{
        color: '#E04845',
        marginLeft: 40,
    },
    inputEmail:{
        elevation: 5,
        shadowColor: "#c55858",
        shadowOffset: { width: 2, height: 12 },
        shadowRadius: 12,
        borderRadius: 15,
        backgroundColor: "#F6F3F4",
        height: 44,
        paddingLeft: 19,
        width: '75%',
        color: '#000',
        marginLeft: 48,
        marginTop: 10,
    },
    inputPass:{
        elevation: 5,
        shadowColor: "#c55858",
        shadowOffset: { width: 9, height: 19 },
        shadowRadius: 19,
        borderRadius: 17,
        backgroundColor: "#F6F3F4",
        height: 44,
        paddingLeft: 19,
        width: '75%',
        color: '#000',
        marginLeft: 48,
        marginTop: 10,
    },
    inputFullN:{
        elevation: 5,
        shadowColor: "#c55858",
        shadowOffset: { width: 9, height: 19 },
        shadowRadius: 19,
        borderRadius: 17,
        backgroundColor: "#F6F3F4",
        height: 44,
        paddingLeft: 19,
        width: '75%',
        color: '#000',
        marginLeft: 48,
        marginTop: 10,
    },
    inputUserN:{
        elevation: 5,
        shadowColor: "#c55858",
        shadowOffset: { width: 9, height: 19 },
        shadowRadius: 19,
        borderRadius: 17,
        backgroundColor: "#F6F3F4",
        height: 44,
        paddingLeft: 19,
        width: '75%',
        color: '#000',
        marginLeft: 48,
        marginTop: 10,
    },
    
    btnRegister:{
        backgroundColor: "#E04845",
        height: 35,
        width: 140,
        marginLeft: 125,
        marginTop: 20,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 5,
        shadowColor: "#c55858",
        shadowOffset: { width: 9, height: 19 },
        shadowRadius: 19,
    },
    textRegister:{
        color: '#FFFFFF',
    }, 
    textLog:{
        color: '#E04845',
        marginTop: 25,
        marginLeft: 130,
    },
    btnLogin:{
        backgroundColor: '#E04845',
        width: 400,
        height: 73.5,
        borderTopLeftRadius: 80,
        borderTopRightRadius: 80,
    },
    textLogin:{
        color: '#FFFFFF',
        marginTop: 20,
        marginLeft: 170,
        fontSize: 20,
    },
    textLineL:{
        color: '#FFFFFF',
        marginLeft: 40,
        marginTop: -10,
    },
});
export default styles;