import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({

    img:{
        width: 400,
        height: 395,
        marginBottom: -95,
    },
    contLog:{
        backgroundColor: '#E04845',
        height: 450,
        width: 400,
        borderTopLeftRadius: 80,
        borderTopRightRadius: 80,
        marginBottom: -70,
    },
    textLog:{
        color: '#FFFFFF',
        marginTop: 20,
        marginLeft: 165,
        fontSize: 20,
    },
    textLineL:{
        color: '#FFFFFF',
        marginLeft: 40,
    },
    inputEmail:{
        elevation: 5,
        shadowColor: "#c55858",
        shadowOffset: { width: 2, height: 12 },
        shadowRadius: 12,
        borderRadius: 15,
        backgroundColor: "#FFFFFF",
        height: 44,
        paddingLeft: 19,
        width: '75%',
        color: '#000',
        marginLeft: 48,
        marginTop: 20,
    },
    inputPass:{
        elevation: 5,
        shadowColor: "#c55858",
        shadowOffset: { width: 9, height: 19 },
        shadowRadius: 19,
        borderRadius: 17,
        backgroundColor: "#FFFFFF",
        height: 44,
        paddingLeft: 19,
        width: '75%',
        color: '#000',
        marginLeft: 48,
        marginTop: 20,
    },
    iconL:{
        fontSize: 25,
        marginLeft: 310,
        marginTop: -35,
        color: '#E04845',
    },
    iconP:{
        fontSize: 25,
        marginLeft: 310,
        marginTop: -35,
        color: '#E04845',
    },
    textFor:{
        color: '#FFFFFF',
        marginTop: 15,
        marginLeft: 110,
    },
    btnClic:{
     backgroundColor: '#E04845',
     height: 20,
     width: 65,
     marginLeft: 225,
     marginTop: -19,
    },
    textClic:{
        color: '#FFFFFF', 
        textDecorationLine: 'underline',
        textDecorationColor: '#FFFFFF'
    },
    btnLogin:{
        backgroundColor: "#FFFFFF",
        height: 35,
        width: 140,
        marginLeft: 125,
        marginTop: 30,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 5,
        shadowColor: "#c55858",
        shadowOffset: { width: 9, height: 19 },
        shadowRadius: 19,
    },
    textLogin:{
        color: '#E04845',
    },
    textOr:{
        color: '#FFFFFF',
        marginTop: 5,
        marginLeft: 140,
    },
    btnGoogle:{
        backgroundColor: "#E04845",
        height: 35,
        width: 120,
        marginLeft: 70,
        marginTop: 10,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: "#FFFFFF",
        borderBottomWidth: 1,
        borderEndWidth: 1,
        borderLeftWidth: 1,
        borderTopWidth: 1,
    },
    iconG:{
        color: '#FFFFFF',
        marginLeft: -50,
        marginTop: -5,
        fontSize: 30,
    },
    textG:{
        color: '#FFFFFF',
        marginTop: -25,
        marginLeft: 25,
    },
    btnFace:{

        backgroundColor: "#E04845",
        height: 35,
        width: 120,
        marginLeft: 205,
        marginTop: -35,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: "#FFFFFF",
        borderBottomWidth: 1,
        borderEndWidth: 1,
        borderLeftWidth: 1,
        borderTopWidth: 1,
    },
    iconF:{
        color: '#FFFFFF',
        marginLeft: -70,
        marginTop: -5,
        fontSize: 30,
    },
    textF:{
        color: '#FFFFFF',
        marginTop: -25,
        marginLeft: 25,
    },
    textReg:{
        color: '#FFFFFF',
        marginTop: 18,
        marginLeft: 135,
    },

    btnRegister:{
        backgroundColor: '#FFFFFF',
        width: 400,
        height: 73,
        borderTopLeftRadius: 80,
        borderTopRightRadius: 80,
    },
    textRegister:{
        color: '#E04845',
        marginTop: 20,
        marginLeft: 150,
        fontSize: 20,
    },
    textLineR:{
        color: '#E04845',
        marginLeft: 40,
        marginTop: -10,
    },
});
export default styles;